apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-security
  labels:
    app: service-security
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-security
  template:
    metadata:
      labels:
        app: service-security
    spec:
      containers:
      - name: service-security
        image: jodagab4/aforo255-security:v2.#{Build.BuildId}#
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: aforo.com
---
kind: Service
apiVersion: v1
metadata:
  name: app-service-security
spec:
  type: LoadBalancer
  selector:
    app: service-security
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

